on:
    workflow_dispatch:
      inputs:
        package_version:
          description: 'Package version to be published to NPM. Defaults to current version of scure-btc-signer.'
          required: false
        dist_tag:
          description: 'What dist tag should be used for publishing (e.g. `next` vs `latest`). Defaults to `next`.'
          required: true
          default: next
  
name: Publish Scure Btc Signer

jobs:
  prebuild-node:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/checkout@v2

        # We're changing scure-btc-signer package.json here and republishing it as a CommonJS module under the name scure-btc-signer-cjs.
      - name: Build CommonJS
        run: |
          yarn install
          node build-scure-btc-signer.mjs

        # Version is set manually, because sometimes (when we make a mistake) we might need to release
        # new versions for the same version of scure-btc-signer-cjs. major.minor should be kept. e.g. scure-btc-signer@12.0.0
        # can be occasionally released as scure-btc-signer-cjs 12.0.1 but not 12.1.0.
      - name: Set version if provided
        if: ${{ github.event.inputs.package_version != null }}
        run: >
          jq '.version = "${{github.event.inputs.package_version}}"' scure-btc-signer/package.json > scure-btc-signer/temp-package.json
          && rm scure-btc-signer/package.json && mv scure-btc-signer/temp-package.json scure-btc-signer/package.json

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: "./scure-btc-signer/package.json"
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: false
          tag: ${{ github.event.inputs.dist_tag }}